# Generated by Django 6.0.1 on 2026-01-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Croprate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tomato_rate', models.PositiveIntegerField(default=0)),
                ('bellpepper_rate', models.PositiveIntegerField(default=0)),
                ('cucumber_rate', models.PositiveIntegerField(default=0)),
                ('abernero_rate', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=40, null=True)),
                ('phone_no', models.IntegerField(blank=True, default=0, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('tomatoes', models.IntegerField(default=0)),
                ('bell_pepper', models.IntegerField(default=0)),
                ('cucumber', models.IntegerField(default=0)),
                ('abernero', models.IntegerField(default=0)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('invoice_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
