# Generated by Django 6.0.1 on 2026-01-14 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='croprate',
            options={'verbose_name': 'Croprate', 'verbose_name_plural': 'Croprate'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoice'},
        ),
    ]
