# Generated by Django 6.0.1 on 2026-01-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_croprate_options_alter_invoice_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cropitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rate', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cropitem',
                'verbose_name_plural': 'Cropitem',
            },
        ),
        migrations.DeleteModel(
            name='Croprate',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
