# Generated by Django 6.0.1 on 2026-01-20 08:58

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cropitem_delete_croprate_alter_invoice_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='image',
            field=models.ImageField(default='avatar.jpg', upload_to='Observation_Images', validators=[app.models.validate_image_size]),
        ),
    ]
