# Generated by Django 6.0.1 on 2026-01-22 00:04

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_invoice_discount_invoice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='image',
            field=models.ImageField(blank=True, upload_to='signatures', validators=[app.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
