# Generated by Django 6.0.1 on 2026-01-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_invoice_email_alter_invoice_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
