# Generated by Django 6.0.1 on 2026-01-24 07:42

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_invoice_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateField(blank=True, null=True, validators=[app.models.validate_not_future]),
        ),
    ]
